Repository automl/Auto-PyTorch, pull requests merged in 2021-04, with the labels that each got.

#121 Run history traditional
  autoPyTorch/api/base_task.py
  autoPyTorch/evaluation/abstract_evaluator.py
  autoPyTorch/evaluation/tae.py
  autoPyTorch/evaluation/train_evaluator.py
  test/test_api/test_api.py
  test/test_evaluation/test_train_evaluator.py
Labels: enhancement

#127 [Doc] First push of the developer documentation
  docs/conf.py
  docs/dev.rst
  docs/index.rst
Labels: Documentation

#173 Fit_pipeline honoring api constraints
  .github/workflows/examples.yml
  .github/workflows/pytest.yml
  autoPyTorch/api/base_task.py
  autoPyTorch/api/tabular_classification.py
  autoPyTorch/api/tabular_regression.py
  autoPyTorch/evaluation/tae.py
  autoPyTorch/optimizer/smbo.py
  examples/tabular/40_advanced/example_single_configuration.py
  setup.py
  test/test_api/test_api.py
Labels: bug

#106 Refactoring base dataset splitting functions
  autoPyTorch/api/base_task.py
  autoPyTorch/datasets/base_dataset.py
  autoPyTorch/datasets/resampling_strategy.py
  autoPyTorch/datasets/time_series_dataset.py
  autoPyTorch/ensemble/ensemble_builder.py
Labels: refactoring
