Repository automl/Auto-PyTorch, pull requests merged in 2021-11, with the labels that each got.

#305 [ADD] Add column transformer
  autoPyTorch/api/base_task.py
  autoPyTorch/data/base_feature_validator.py
  autoPyTorch/data/tabular_feature_validator.py
  autoPyTorch/pipeline/components/setup/network_backbone/InceptionTimeBackbone.py
  autoPyTorch/pipeline/components/setup/traditional_ml/estimator_configs/extra_trees.json
  autoPyTorch/pipeline/components/setup/traditional_ml/estimator_configs/knn.json
  autoPyTorch/pipeline/components/setup/traditional_ml/estimator_configs/lgb.json
  autoPyTorch/pipeline/components/setup/traditional_ml/estimator_configs/random_forest.json
  autoPyTorch/pipeline/components/setup/traditional_ml/estimator_configs/rotation_forest.json
  examples/40_advanced/example_custom_configuration_space.py
  requirements.txt
  test/test_api/test_base_api.py
  test/test_data/test_feature_validator.py
Labels: enhancement

#317 [ADD] Missing Batchnorm
  autoPyTorch/pipeline/components/setup/network_backbone/MLPBackbone.py
  autoPyTorch/pipeline/components/setup/network_backbone/ShapedMLPBackbone.py
  autoPyTorch/pipeline/components/training/data_loader/base_data_loader.py
  test/test_pipeline/test_tabular_classification.py
Labels: first priority

#316 [FIX] Additional metrics during training
  autoPyTorch/evaluation/abstract_evaluator.py
  test/test_evaluation/test_abstract_evaluator.py
  test/test_evaluation/test_train_evaluator.py
Labels: bug

#320 [ADD] Update developer documentation
  docs/dev.rst
Labels: Documentation

#321 [FIX] remove .pth for early stopping
  autoPyTorch/pipeline/components/training/trainer/__init__.py
  test/test_pipeline/components/training/test_training.py
Labels: bug

#322 [Add] documentation and example for parallel computation
  docs/manual.rst
  examples/40_advanced/README.txt
  examples/40_advanced/example_parallel_n_jobs.py
Labels: Documentation

#323 [ADD] Documentation for data validation and preprocessing
  autoPyTorch/api/base_task.py
  autoPyTorch/api/tabular_classification.py
  autoPyTorch/api/tabular_regression.py
  autoPyTorch/datasets/base_dataset.py
  autoPyTorch/datasets/image_dataset.py
  autoPyTorch/datasets/tabular_dataset.py
  autoPyTorch/optimizer/smbo.py
  autoPyTorch/pipeline/components/setup/traditional_ml/traditional_learner/base_traditional_learner.py
  autoPyTorch/pipeline/components/training/metrics/base.py
  autoPyTorch/utils/pipeline.py
  docs/installation.rst
  docs/manual.rst
  docs/releases.rst
Labels: Documentation

#329 [ADD] documentation for pipelines and steps
  autoPyTorch/api/tabular_classification.py
  autoPyTorch/api/tabular_regression.py
  autoPyTorch/pipeline/base_pipeline.py
  autoPyTorch/pipeline/components/base_choice.py
  autoPyTorch/pipeline/components/base_component.py
  autoPyTorch/pipeline/tabular_classification.py
  autoPyTorch/pipeline/tabular_regression.py
  autoPyTorch/pipeline/traditional_tabular_classification.py
  autoPyTorch/pipeline/traditional_tabular_regression.py
  docs/api.rst
Labels: Documentation

#334 [feat] Support statistics print by adding results manager object
  autoPyTorch/api/base_task.py
  autoPyTorch/api/results_manager.py
  autoPyTorch/api/tabular_classification.py
  autoPyTorch/api/tabular_regression.py
  autoPyTorch/evaluation/abstract_evaluator.py
  examples/20_basics/example_tabular_classification.py
  examples/20_basics/example_tabular_regression.py
  examples/40_advanced/example_custom_configuration_space.py
  examples/40_advanced/example_resampling_strategy.py
  examples/40_advanced/example_run_with_portfolio.py
  examples/40_advanced/example_visualization.py
  test/test_api/.tmp_api/runhistory_B.json
  test/test_api/test_api.py
  test/test_api/test_results_manager.py
  test/test_api/utils.py
Labels: enhancement

#136 [feat] Add an issue template and a PR template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, Documentation

#285 [doc] Add the workflow of the Auto-Pytorch
  README.md
  figs/apt_workflow.png
Labels: Documentation

#340 [FIX] Incorrect cost for crash, r2
  autoPyTorch/pipeline/components/training/metrics/metrics.py
Labels: bug, first priority
