Repository automl/Auto-PyTorch, pull requests merged in 2021-03, with the labels that each got.

#118 handle nans in categorical columns
  autoPyTorch/data/tabular_feature_validator.py
  test/test_data/test_feature_validator.py
Labels: bug

#112 Pre fetch openml data for pytest
  setup.py
  test/conftest.py
Labels: enhancement

#120 Match paper libraries-versions
  requirements.txt
Labels: bug

#126 Fixes to address automlbenchmark problems
  autoPyTorch/api/base_task.py
  autoPyTorch/data/tabular_feature_validator.py
  autoPyTorch/evaluation/abstract_evaluator.py
  test/test_api/test_api.py
  test/test_data/test_feature_validator.py
Labels: bug

#105 Refactoring base dataset
  autoPyTorch/datasets/base_dataset.py
  test/conftest.py
Labels: refactoring

#113 move to a minimization problem
  .github/workflows/pytest.yml
  autoPyTorch/ensemble/ensemble_builder.py
  autoPyTorch/ensemble/ensemble_selection.py
  autoPyTorch/evaluation/abstract_evaluator.py
  autoPyTorch/pipeline/components/training/metrics/utils.py
  test/test_api/test_api.py
  test/test_ensemble/test_ensemble.py
  test/test_pipeline/components/preprocessing/test_feature_preprocessor.py
  test/test_pipeline/test_metrics.py
  test/test_pipeline/test_tabular_classification.py
  test/test_pipeline/test_tabular_regression.py
Labels: enhancement

#133 FIX_123
  autoPyTorch/api/base_task.py
  autoPyTorch/configs/default_pipeline_options.json
  autoPyTorch/pipeline/base_pipeline.py
  autoPyTorch/pipeline/components/training/trainer/base_trainer.py
  autoPyTorch/pipeline/components/training/trainer/base_trainer_choice.py
  test/conftest.py
  test/test_api/test_api.py
  test/test_pipeline/test_tabular_classification.py
  test/test_pipeline/test_tabular_regression.py
Labels: bug

#124 Adds more examples to customise AutoPyTorch.
  .github/workflows/examples.yml
  autoPyTorch/api/tabular_classification.py
  autoPyTorch/datasets/resampling_strategy.py
  autoPyTorch/utils/hyperparameter_search_space_update.py
  docs/conf.py
  examples/tabular/20_basics/README.txt
  examples/tabular/20_basics/example_tabular_classification.py
  examples/tabular/20_basics/example_tabular_regression.py
  examples/tabular/40_advanced/README.txt
  examples/tabular/40_advanced/example_custom_configuration_space.py
  examples/tabular/40_advanced/example_resampling_strategy.py
Labels: Documentation

#147 [Bug] Fix random halt problems on traditional pipelines
  autoPyTorch/evaluation/abstract_evaluator.py
  test/test_pipeline/components/preprocessing/test_feature_preprocessor.py
Labels: bug
