Repository automl/Auto-PyTorch, pull requests merged in 2021-05, with the labels that each got.

#190 [Feature] Introduces no resampling strategy to enable fitting on the whole dataset
  autoPyTorch/api/base_task.py
  autoPyTorch/api/tabular_classification.py
  autoPyTorch/api/tabular_regression.py
  autoPyTorch/datasets/base_dataset.py
  autoPyTorch/datasets/image_dataset.py
  autoPyTorch/datasets/resampling_strategy.py
  autoPyTorch/datasets/tabular_dataset.py
  autoPyTorch/evaluation/abstract_evaluator.py
  autoPyTorch/evaluation/fit_evaluator.py
  autoPyTorch/evaluation/tae.py
  autoPyTorch/evaluation/train_evaluator.py
  autoPyTorch/pipeline/components/training/data_loader/base_data_loader.py
  autoPyTorch/pipeline/components/training/trainer/AdversarialTrainer.py
  autoPyTorch/pipeline/components/training/trainer/StandardTrainer.py
  autoPyTorch/pipeline/components/training/trainer/base_trainer.py
  autoPyTorch/pipeline/components/training/trainer/base_trainer_choice.py
  autoPyTorch/pipeline/components/training/trainer/cutout_utils.py
  autoPyTorch/pipeline/components/training/trainer/mixup_utils.py
  examples/tabular/40_advanced/example_single_configuration.py
  test/test_api/test_api.py
  test/test_evaluation/test_fit_evaluator.py
  test/test_pipeline/test_tabular_classification.py
Labels: enhancement

#172 [Fix] Refactor development reproducibility
  .github/workflows/pytest.yml
  autoPyTorch/api/base_task.py
  autoPyTorch/datasets/base_dataset.py
  autoPyTorch/datasets/resampling_strategy.py
  autoPyTorch/evaluation/abstract_evaluator.py
  autoPyTorch/evaluation/tae.py
  autoPyTorch/pipeline/base_pipeline.py
  autoPyTorch/pipeline/components/base_component.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/feature_preprocessing/TruncatedSVD.py
  autoPyTorch/pipeline/components/setup/network_backbone/utils.py
  autoPyTorch/pipeline/components/setup/traditional_ml/base_model.py
  autoPyTorch/pipeline/components/setup/traditional_ml/classifier_models/base_classifier.py
  autoPyTorch/pipeline/components/setup/traditional_ml/classifier_models/classifiers.py
  autoPyTorch/pipeline/components/setup/traditional_ml/tabular_classifier.py
  autoPyTorch/pipeline/components/training/base_training.py
  autoPyTorch/pipeline/components/training/data_loader/base_data_loader.py
  autoPyTorch/pipeline/components/training/trainer/MixUpTrainer.py
  autoPyTorch/pipeline/components/training/trainer/base_trainer.py
  autoPyTorch/pipeline/tabular_classification.py
  autoPyTorch/pipeline/tabular_regression.py
  autoPyTorch/pipeline/traditional_tabular_classification.py
  examples/tabular/20_basics/example_tabular_classification.py
  setup.py
  test/test_api/test_api.py
  test/test_evaluation/test_train_evaluator.py
  test/test_pipeline/test_tabular_classification.py
Labels: bug

#189 [ADD] Extra visualization example
  autoPyTorch/__version__.py
  autoPyTorch/api/base_task.py
  docs/manual.rst
  docs/releases.rst
  examples/tabular/40_advanced/example_visualization.py
Labels: Documentation

#205 Reduce run time of the test
  .github/workflows/examples.yml
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/feature_preprocessing/KernelPCA.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/feature_preprocessing/Nystroem.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/feature_preprocessing/PolynomialFeatures.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/feature_preprocessing/PowerTransformer.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/feature_preprocessing/RandomKitchenSinks.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/feature_preprocessing/TruncatedSVD.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/feature_preprocessing/base_feature_preprocessor.py
  test/conftest.py
  test/test_api/test_api.py
  test/test_api/utils.py
  test/test_ensemble/test_ensemble.py
  test/test_pipeline/components/preprocessing/test_feature_preprocessor.py
  test/test_pipeline/components/setup/test_setup_networks.py
  test/test_pipeline/components/training/base.py
  test/test_pipeline/components/training/test_training.py
  test/test_pipeline/test_tabular_classification.py
  test/test_pipeline/test_tabular_regression.py
Labels: enhancement

#164 [refactor] Getting dataset properties from the dataset object
  autoPyTorch/api/base_task.py
  autoPyTorch/api/tabular_classification.py
  autoPyTorch/api/tabular_regression.py
  autoPyTorch/datasets/base_dataset.py
  autoPyTorch/datasets/tabular_dataset.py
  autoPyTorch/evaluation/abstract_evaluator.py
  autoPyTorch/utils/pipeline.py
Labels: refactoring

#200 [feature] Greedy Portfolio
  autoPyTorch/api/base_task.py
  autoPyTorch/api/tabular_classification.py
  autoPyTorch/api/tabular_regression.py
  autoPyTorch/configs/greedy_portfolio.json
  autoPyTorch/optimizer/smbo.py
  autoPyTorch/optimizer/utils.py
  autoPyTorch/pipeline/base_pipeline.py
  autoPyTorch/pipeline/image_classification.py
  autoPyTorch/pipeline/tabular_classification.py
  autoPyTorch/pipeline/tabular_regression.py
  autoPyTorch/pipeline/traditional_tabular_classification.py
  examples/40_advanced/example_run_with_portfolio.py
  setup.py
  test/test_api/test_api.py
  test/test_pipeline/components/training/base.py
  test/test_pipeline/components/training/test_training.py
Labels: enhancement
