Repository automl/Auto-PyTorch, pull requests merged in 2022-02, with the labels that each got.

#373 [ADD] variance thresholding
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/variance_thresholding/VarianceThreshold.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/variance_thresholding/__init__.py
  autoPyTorch/pipeline/tabular_classification.py
  autoPyTorch/pipeline/tabular_regression.py
  test/test_pipeline/components/preprocessing/base.py
  test/test_pipeline/components/preprocessing/test_variance_thresholding.py
Labels: autosklearn-migrate

#372 [ADD] scalers from autosklearn
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/feature_preprocessing/PowerTransformer.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/feature_preprocessing/__init__.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/scaling/PowerTransformer.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/scaling/QuantileTransformer.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/scaling/RobustScaler.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/scaling/__init__.py
  test/test_pipeline/components/preprocessing/test_feature_preprocessor.py
  test/test_pipeline/components/preprocessing/test_scalers.py
Labels: autosklearn-migrate

#375 [FIX] Remove redundant categorical imputation
  autoPyTorch/configs/greedy_portfolio.json
  autoPyTorch/optimizer/smbo.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/TabularColumnTransformer.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/imputation/SimpleImputer.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/imputation/base_imputer.py
  test/test_pipeline/components/preprocessing/test_imputers.py
Labels: bug

#376 [feat] Add coalescer
  autoPyTorch/configs/greedy_portfolio.json
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/coalescer/MinorityCoalescer.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/coalescer/NoCoalescer.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/coalescer/__init__.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/coalescer/base_coalescer.py
  autoPyTorch/pipeline/tabular_classification.py
  autoPyTorch/pipeline/tabular_regression.py
  autoPyTorch/utils/implementations.py
  test/test_api/.tmp_api/runhistory.json
  test/test_pipeline/components/preprocessing/base.py
  test/test_pipeline/components/preprocessing/test_coalescer.py
  test/test_utils/runhistory.json
  test/test_utils/test_coalescer_transformer.py
Labels: autosklearn-migrate

#369 [FIX] Enable preprocessing in reg_cocktails
  autoPyTorch/api/tabular_classification.py
  autoPyTorch/api/tabular_regression.py
  autoPyTorch/data/tabular_feature_validator.py
  autoPyTorch/datasets/base_dataset.py
  autoPyTorch/datasets/resampling_strategy.py
  autoPyTorch/evaluation/fit_evaluator.py
  autoPyTorch/evaluation/train_evaluator.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/TabularColumnTransformer.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/encoding/NoEncoder.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/encoding/base_encoder.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/imputation/base_imputer.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/scaling/NoScaler.py
  autoPyTorch/pipeline/components/preprocessing/tabular_preprocessing/scaling/base_scaler.py
  autoPyTorch/pipeline/components/setup/early_preprocessor/EarlyPreprocessing.py
  autoPyTorch/pipeline/components/setup/lr_scheduler/base_scheduler.py
  autoPyTorch/pipeline/components/setup/network/base_network.py
  autoPyTorch/pipeline/components/setup/network_backbone/base_network_backbone.py
  autoPyTorch/pipeline/components/setup/network_embedding/base_network_embedding.py
  autoPyTorch/pipeline/components/training/data_loader/base_data_loader.py
  autoPyTorch/pipeline/components/training/data_loader/feature_data_loader.py
  autoPyTorch/pipeline/components/training/data_loader/image_data_loader.py
  autoPyTorch/pipeline/components/training/trainer/AdversarialTrainer.py
  autoPyTorch/pipeline/components/training/trainer/__init__.py
  autoPyTorch/pipeline/components/training/trainer/base_trainer.py
  test/test_data/test_feature_validator.py
  test/test_data/test_validation.py
  test/test_datasets/test_tabular_dataset.py
  test/test_evaluation/test_fit_evaluator.py
  test/test_pipeline/components/preprocessing/test_encoders.py
  test/test_pipeline/components/preprocessing/test_imputers.py
  test/test_pipeline/components/preprocessing/test_scalers.py
  test/test_pipeline/components/preprocessing/test_tabular_column_transformer.py
  test/test_pipeline/components/training/test_feature_data_loader.py
  test/test_pipeline/components/training/test_training.py
Labels: enhancement
